#!/usr/bin/env python3
"""Apply prepared hard-case feedback payloads, dry-run by default.

The input JSONL is produced by `prepare_hard_case_feedback_payloads.py` or the
review pipeline. By default this tool only validates and reports what would be
sent. Network calls require an explicit `--apply` flag plus a `--base-url` and a
Bearer token from `--bearer-token` or `CICERO_API_BEARER_TOKEN`.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from collections import Counter
from pathlib import Path
from typing import Any

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from tools.validate_hard_cases_csv import ALLOWED_FEEDBACK

REQUIRED_FIELDS = {"scan_id", "method", "path", "payload"}
FORBIDDEN_FIELDS = {
    "embedding",
    "raw_embedding",
    "image",
    "raw_image",
    "photo",
    "location",
    "lat",
    "lng",
    "latitude",
    "longitude",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate and optionally POST hard-case feedback payloads; dry-run is the default."
    )
    parser.add_argument("input_jsonl", type=Path, help="JSONL generated by prepare_hard_case_feedback_payloads.py")
    parser.add_argument("--base-url", help="API base URL, e.g. http://127.0.0.1:8000; required with --apply")
    parser.add_argument("--bearer-token", help="Bearer token; fallback: CICERO_API_BEARER_TOKEN")
    parser.add_argument("--timeout", type=float, default=10.0, help="HTTP timeout in seconds when --apply is used")
    parser.add_argument("--apply", action="store_true", help="Actually POST payloads to the API; otherwise dry-run only")
    parser.add_argument("--json", action="store_true", help="Print a machine-readable report")
    return parser.parse_args()


def _forbidden_paths(value: Any, prefix: str = "") -> list[str]:
    paths: list[str] = []
    if isinstance(value, dict):
        for key, nested in value.items():
            path = f"{prefix}.{key}" if prefix else str(key)
            if str(key) in FORBIDDEN_FIELDS:
                paths.append(path)
            paths.extend(_forbidden_paths(nested, path))
    elif isinstance(value, list):
        for index, nested in enumerate(value):
            paths.extend(_forbidden_paths(nested, f"{prefix}[{index}]"))
    return paths


def _validate_record(record: Any, line_number: int) -> tuple[dict[str, Any] | None, list[str]]:
    errors: list[str] = []
    if not isinstance(record, dict):
        return None, [f"line {line_number}: record must be a JSON object"]

    missing = REQUIRED_FIELDS - set(record)
    if missing:
        errors.append(f"line {line_number}: missing field(s): {', '.join(sorted(missing))}")

    scan_id = str(record.get("scan_id") or "").strip()
    method = str(record.get("method") or "").strip().upper()
    path = str(record.get("path") or "").strip()
    payload = record.get("payload")

    if not scan_id:
        errors.append(f"line {line_number}: scan_id must be non-empty")
    if method != "POST":
        errors.append(f"line {line_number}: method must be POST")
    if path != f"/v1/hard-cases/{scan_id}/feedback":
        errors.append(f"line {line_number}: path must target /v1/hard-cases/<scan_id>/feedback")
    if not isinstance(payload, dict):
        errors.append(f"line {line_number}: payload must be an object")
    else:
        feedback = str(payload.get("user_feedback") or "").strip()
        if feedback not in ALLOWED_FEEDBACK:
            errors.append(f"line {line_number}: payload.user_feedback is not an allowed label")
        notes = payload.get("notes")
        if notes is not None and (not isinstance(notes, str) or len(notes.strip()) > 240):
            errors.append(f"line {line_number}: payload.notes must be a string up to 240 characters")
        allowed_payload_fields = {"user_feedback", "notes"}
        extra_payload_fields = set(payload) - allowed_payload_fields
        if extra_payload_fields:
            errors.append(
                f"line {line_number}: payload has unsupported field(s): {', '.join(sorted(extra_payload_fields))}"
            )

    forbidden = _forbidden_paths(record)
    if forbidden:
        errors.append(f"line {line_number}: forbidden privacy field(s): {', '.join(forbidden)}")

    if errors:
        return None, errors
    return {"scan_id": scan_id, "method": method, "path": path, "payload": payload}, []


def load_payloads(input_jsonl: Path) -> dict[str, Any]:
    """Load and validate prepared JSONL payloads without sending them."""
    errors: list[str] = []
    records: list[dict[str, Any]] = []
    seen_scan_ids: set[str] = set()
    feedback_counts: Counter[str] = Counter()

    with input_jsonl.open(encoding="utf-8") as input_file:
        for line_number, line in enumerate(input_file, start=1):
            if not line.strip():
                continue
            try:
                raw_record = json.loads(line)
            except json.JSONDecodeError as exc:
                errors.append(f"line {line_number}: invalid JSON: {exc.msg}")
                continue
            record, record_errors = _validate_record(raw_record, line_number)
            errors.extend(record_errors)
            if record is None:
                continue
            if record["scan_id"] in seen_scan_ids:
                errors.append(f"line {line_number}: duplicate scan_id={record['scan_id']}")
                continue
            seen_scan_ids.add(record["scan_id"])
            feedback_counts[record["payload"]["user_feedback"]] += 1
            records.append(record)

    return {
        "schema_version": "hard-case-feedback-apply-v1",
        "valid": not errors,
        "input_jsonl": str(input_jsonl),
        "payload_count": len(records) if not errors else 0,
        "counts_by_feedback": dict(sorted(feedback_counts.items())) if not errors else {},
        "errors": errors,
        "records": records if not errors else [],
        "privacy": {
            "sends_raw_image": False,
            "sends_raw_embedding": False,
            "sends_precise_location": False,
        },
    }


def _post_feedback(base_url: str, token: str, record: dict[str, Any], timeout: float) -> dict[str, Any]:
    url = base_url.rstrip("/") + record["path"]
    body = json.dumps(record["payload"], ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=body,
        method="POST",
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:  # nosec B310 - explicit ops URL
            response_body = response.read().decode("utf-8")
            return {
                "scan_id": record["scan_id"],
                "ok": 200 <= response.status < 300,
                "status_code": response.status,
                "body": json.loads(response_body) if response_body else None,
            }
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8")
        return {
            "scan_id": record["scan_id"],
            "ok": False,
            "status_code": exc.code,
            "body": body,
        }
    except urllib.error.URLError as exc:
        return {"scan_id": record["scan_id"], "ok": False, "error": str(exc.reason)}


def apply_payloads(
    input_jsonl: Path,
    *,
    apply: bool = False,
    base_url: str | None = None,
    bearer_token: str | None = None,
    timeout: float = 10.0,
) -> dict[str, Any]:
    """Validate payloads and optionally POST them. Default is dry-run only."""
    report = load_payloads(input_jsonl)
    report["mode"] = "apply" if apply else "dry_run"
    report["base_url"] = base_url.rstrip("/") if base_url else None
    report["applied_count"] = 0
    report["failed_count"] = 0
    report["results"] = []

    if not report["valid"] or not apply:
        report.pop("records", None)
        return report

    token = bearer_token or os.getenv("CICERO_API_BEARER_TOKEN")
    if not base_url:
        report["valid"] = False
        report["errors"].append("--base-url is required with --apply")
        report.pop("records", None)
        return report
    if not token:
        report["valid"] = False
        report["errors"].append("--bearer-token or CICERO_API_BEARER_TOKEN is required with --apply")
        report.pop("records", None)
        return report

    results = [_post_feedback(base_url, token, record, timeout) for record in report["records"]]
    applied_count = sum(1 for result in results if result.get("ok"))
    report["results"] = results
    report["applied_count"] = applied_count
    report["failed_count"] = len(results) - applied_count
    report.pop("records", None)
    return report


def main() -> int:
    args = parse_args()
    report = apply_payloads(
        args.input_jsonl,
        apply=args.apply,
        base_url=args.base_url,
        bearer_token=args.bearer_token,
        timeout=args.timeout,
    )
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    elif report["valid"]:
        if report["mode"] == "dry_run":
            print(f"dry-run ok: {report['payload_count']} feedback payload(s) validated, 0 sent")
        else:
            print(
                f"apply complete: {report['applied_count']} sent, {report['failed_count']} failed "
                f"from {report['payload_count']} payload(s)"
            )
    else:
        print(f"payloads invalid: {len(report['errors'])} error(s), 0 sent")
    return 0 if report["valid"] and report["failed_count"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
