#!/usr/bin/env python3
"""Export a human-readable Markdown review sheet from a hard-case batch JSON.

The input is the privacy-safe JSON generated by `select_hard_case_review_batch.py`
or by the review pipeline. The output is intentionally printable/non-technical:
reviewers can mark a label and add notes without seeing raw images, embeddings or
precise location data.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ALLOWED_LABELS = ["correct", "wrong_monument", "unknown", "poor_angle", "too_dark", "other"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a printable Markdown sheet from a privacy-safe hard-case review batch."
    )
    parser.add_argument("input_json", type=Path, help="JSON generated by select_hard_case_review_batch.py")
    parser.add_argument("output_md", type=Path, help="Destination Markdown path")
    return parser.parse_args()


def _read_batch(input_json: Path) -> dict[str, Any]:
    batch = json.loads(input_json.read_text(encoding="utf-8"))
    if batch.get("schema_version") != "hard-case-review-batch-v1":
        raise ValueError("input JSON must use schema_version=hard-case-review-batch-v1")
    if not isinstance(batch.get("items"), list):
        raise ValueError("input JSON must contain an items list")
    return batch


def _format_candidate(value: Any) -> str:
    text = "" if value is None else str(value).strip()
    return text or "—"


def render_markdown(batch: dict[str, Any]) -> str:
    """Render the batch as a compact reviewer worksheet."""
    items = batch["items"]
    lines = [
        "# Cicero — Fiche de revue cas difficiles",
        "",
        f"- Source: `{batch.get('source_csv', '')}`",
        f"- Cas sélectionnés: {batch.get('selected_count', len(items))} / non résolus: {batch.get('unresolved_count', 0)} / total CSV: {batch.get('input_record_count', 0)}",
        f"- Effort revue estimé: {batch.get('estimated_review_effort_minutes', 0)} min",
        f"- Politique: priorité décroissante, plafonds ville/statut `{json.dumps(batch.get('selection_policy', {}), ensure_ascii=False)}`",
        "- Confidentialité: aucune image brute, aucun embedding brut, aucune position précise dans cette fiche.",
        "",
        "## Labels autorisés",
        "",
        ", ".join(f"`{label}`" for label in ALLOWED_LABELS),
        "",
        "## À annoter",
        "",
    ]

    if not items:
        lines.extend(["Aucun cas à revoir dans ce batch.", ""])
        return "\n".join(lines)

    for index, item in enumerate(items, start=1):
        lines.extend(
            [
                f"### {index}. `{item['scan_id']}` — priorité {item['review_priority']}",
                "",
                f"- Effort estimé: {item.get('review_effort_minutes', 0)} min",
                f"- Statut: `{item['status']}`",
                f"- Score: {item['score']}",
                f"- Ville: `{item['city_id']}`",
                f"- Candidat modèle: {_format_candidate(item.get('candidate_monument_id'))}",
                f"- Créé le: `{item['created_at']}`",
                f"- Version modèle: `{item['model_version']}`",
                f"- Feedback actuel: `{item.get('user_feedback') or ''}`",
                f"- Notes actuelles: {_format_candidate(item.get('notes'))}",
                "",
                "Décision revue:",
                "- [ ] correct",
                "- [ ] wrong_monument",
                "- [ ] unknown",
                "- [ ] poor_angle",
                "- [ ] too_dark",
                "- [ ] other",
                "",
                "Notes revue: ________________________________________________",
                "",
            ]
        )
    return "\n".join(lines)


def export_review_markdown(input_json: Path, output_md: Path) -> dict[str, Any]:
    batch = _read_batch(input_json)
    markdown = render_markdown(batch)
    output_md.parent.mkdir(parents=True, exist_ok=True)
    output_md.write_text(markdown, encoding="utf-8")
    return {
        "schema_version": "hard-case-review-markdown-export-v1",
        "input_json": str(input_json),
        "output_md": str(output_md),
        "item_count": len(batch["items"]),
    }


def main() -> int:
    args = parse_args()
    report = export_review_markdown(args.input_json, args.output_md)
    print(f"review markdown: {report['item_count']} item(s) to {args.output_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
