#!/usr/bin/env python3
"""Import reviewer decisions from a Cicero hard-case Markdown sheet into CSV.

The input Markdown is generated by `export_hard_case_review_markdown.py` and
filled manually by checking exactly one label per reviewed `scan_id`. This tool
updates a privacy-safe hard-case CSV without calling the API and without mutating
the hard-case JSONL store.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path
from typing import Any

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from tools.validate_hard_cases_csv import ALLOWED_FEEDBACK, REQUIRED_FIELDS, validate_csv

SECTION_RE = re.compile(r"^###\s+\d+\.\s+`(?P<scan_id>[^`]+)`")
CHECKBOX_RE = re.compile(r"^- \[(?P<mark>[xX ])\]\s+(?P<label>[a-z_]+)\s*$")
NOTES_RE = re.compile(r"^Notes revue:\s*(?P<notes>.*)$")
PLACEHOLDER_NOTES = "________________________________________________"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Apply checked Markdown review decisions to a privacy-safe hard-case CSV."
    )
    parser.add_argument("input_csv", type=Path, help="CSV generated by tools/export_hard_cases_csv.py")
    parser.add_argument("input_md", type=Path, help="Annotated Markdown generated by export_hard_case_review_markdown.py")
    parser.add_argument("output_csv", type=Path, help="Destination annotated CSV path")
    parser.add_argument(
        "--require-decision-for-each-section",
        action="store_true",
        help="Fail if a Markdown case section has no checked decision label.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the full machine-readable import report instead of a compact line.",
    )
    return parser.parse_args()


def _clean_notes(raw_notes: str) -> str | None:
    notes = raw_notes.strip()
    if not notes or notes == PLACEHOLDER_NOTES or set(notes) <= {"_"}:
        return None
    return notes


def parse_markdown_decisions(
    input_md: Path, *, require_decision_for_each_section: bool = False
) -> dict[str, Any]:
    """Parse checked labels and optional notes from a review Markdown sheet."""
    decisions: dict[str, dict[str, str | None]] = {}
    errors: list[str] = []
    section_count = 0
    current_scan_id: str | None = None
    checked_labels: list[str] = []
    notes: str | None = None

    def flush_current() -> None:
        nonlocal current_scan_id, checked_labels, notes
        if current_scan_id is None:
            return
        if len(checked_labels) > 1:
            errors.append(
                f"section {current_scan_id}: exactly one checked label expected, got {len(checked_labels)}"
            )
        elif len(checked_labels) == 1:
            decisions[current_scan_id] = {"user_feedback": checked_labels[0], "notes": notes}
        elif require_decision_for_each_section:
            errors.append(f"section {current_scan_id}: no checked decision label")
        current_scan_id = None
        checked_labels = []
        notes = None

    for line_number, line in enumerate(input_md.read_text(encoding="utf-8").splitlines(), start=1):
        section_match = SECTION_RE.match(line)
        if section_match:
            flush_current()
            section_count += 1
            current_scan_id = section_match.group("scan_id").strip()
            if not current_scan_id:
                errors.append(f"line {line_number}: scan_id must be non-empty")
            continue

        if current_scan_id is None:
            continue

        checkbox_match = CHECKBOX_RE.match(line)
        if checkbox_match:
            label = checkbox_match.group("label")
            if label not in ALLOWED_FEEDBACK:
                errors.append(f"line {line_number}: label {label} is not allowed")
                continue
            if checkbox_match.group("mark") in {"x", "X"}:
                checked_labels.append(label)
            continue

        notes_match = NOTES_RE.match(line)
        if notes_match:
            notes = _clean_notes(notes_match.group("notes"))

    flush_current()
    return {
        "schema_version": "hard-case-review-markdown-decisions-v1",
        "input_md": str(input_md),
        "section_count": section_count,
        "decision_count": len(decisions),
        "decisions": decisions,
        "errors": errors,
    }


def import_markdown_decisions(
    input_csv: Path,
    input_md: Path,
    output_csv: Path,
    *,
    require_decision_for_each_section: bool = False,
) -> dict[str, Any]:
    """Write a new CSV with Markdown decisions applied by `scan_id`."""
    csv_validation = validate_csv(input_csv)
    if not csv_validation["valid"]:
        return {
            "schema_version": "hard-case-review-markdown-import-v1",
            "input_csv": str(input_csv),
            "input_md": str(input_md),
            "output_csv": str(output_csv),
            "valid": False,
            "csv_validation": csv_validation,
            "markdown": None,
            "applied_count": 0,
            "errors": ["input CSV is invalid; aborting import"],
        }

    markdown = parse_markdown_decisions(
        input_md, require_decision_for_each_section=require_decision_for_each_section
    )
    errors = list(markdown["errors"])

    with input_csv.open(encoding="utf-8", newline="") as input_file:
        reader = csv.DictReader(input_file)
        fieldnames = list(reader.fieldnames or [])
        missing = REQUIRED_FIELDS - set(fieldnames)
        if missing:
            errors.append(f"CSV missing required field(s): {', '.join(sorted(missing))}")
        rows = [dict(row) for row in reader]

    scan_ids = {row.get("scan_id", "") for row in rows}
    for scan_id in markdown["decisions"]:
        if scan_id not in scan_ids:
            errors.append(f"Markdown decision references unknown scan_id={scan_id}")

    if errors:
        return {
            "schema_version": "hard-case-review-markdown-import-v1",
            "input_csv": str(input_csv),
            "input_md": str(input_md),
            "output_csv": str(output_csv),
            "valid": False,
            "csv_validation": csv_validation,
            "markdown": markdown,
            "applied_count": 0,
            "errors": errors,
        }

    applied_count = 0
    decisions = markdown["decisions"]
    for row in rows:
        scan_id = row.get("scan_id", "")
        decision = decisions.get(scan_id)
        if not decision:
            continue
        row["user_feedback"] = str(decision["user_feedback"])
        if decision.get("notes") is not None:
            row["notes"] = str(decision["notes"])
        applied_count += 1

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", encoding="utf-8", newline="") as output_file:
        writer = csv.DictWriter(output_file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    output_validation = validate_csv(output_csv)
    return {
        "schema_version": "hard-case-review-markdown-import-v1",
        "input_csv": str(input_csv),
        "input_md": str(input_md),
        "output_csv": str(output_csv),
        "valid": output_validation["valid"],
        "csv_validation": csv_validation,
        "markdown": markdown,
        "output_validation": output_validation,
        "applied_count": applied_count,
        "errors": output_validation["errors"],
    }


def main() -> int:
    args = parse_args()
    report = import_markdown_decisions(
        args.input_csv,
        args.input_md,
        args.output_csv,
        require_decision_for_each_section=args.require_decision_for_each_section,
    )
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    elif report["valid"]:
        print(
            f"imported {report['applied_count']} markdown decision(s) "
            f"to {args.output_csv}"
        )
    else:
        print(
            f"import invalid: {len(report['errors'])} error(s), "
            f"0 decision(s) written"
        )
    return 0 if report["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
