#!/usr/bin/env python3
"""Prepare privacy-safe feedback payloads from an annotated hard-case CSV.

This helper is deliberately dry-run only: it validates the review CSV and emits
one JSONL payload per annotated row. Operators can inspect or pipe the output to
a separate, explicit reinjection step; this script does not call the API.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from tools.validate_hard_cases_csv import validate_csv


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build JSONL feedback payloads from an annotated hard-case review CSV without API side effects."
    )
    parser.add_argument("input_csv", type=Path, help="Annotated CSV generated by tools/export_hard_cases_csv.py")
    parser.add_argument("output_jsonl", type=Path, help="Destination JSONL containing scan_id + payload objects")
    parser.add_argument(
        "--require-all-annotated",
        action="store_true",
        help="Fail if at least one row has no user_feedback label.",
    )
    return parser.parse_args()


def build_payloads(input_csv: Path, output_jsonl: Path, *, require_all_annotated: bool = False) -> dict[str, Any]:
    """Validate input_csv, then write one reinjection payload per annotated row."""
    validation = validate_csv(input_csv, require_all_annotated=require_all_annotated)
    if not validation["valid"]:
        return {
            "schema_version": "hard-case-feedback-payloads-v1",
            "valid": False,
            "payload_count": 0,
            "validation": validation,
        }

    payload_count = 0
    output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    with input_csv.open(encoding="utf-8", newline="") as input_file, output_jsonl.open(
        "w", encoding="utf-8"
    ) as output_file:
        reader = csv.DictReader(input_file)
        for row in reader:
            feedback = (row.get("user_feedback") or "").strip()
            if not feedback:
                continue
            payload: dict[str, str] = {"user_feedback": feedback}
            notes = (row.get("notes") or "").strip()
            if notes:
                payload["notes"] = notes
            output_file.write(
                json.dumps(
                    {
                        "scan_id": (row.get("scan_id") or "").strip(),
                        "method": "POST",
                        "path": f"/v1/hard-cases/{(row.get('scan_id') or '').strip()}/feedback",
                        "payload": payload,
                    },
                    ensure_ascii=False,
                    sort_keys=True,
                )
                + "\n"
            )
            payload_count += 1

    return {
        "schema_version": "hard-case-feedback-payloads-v1",
        "valid": True,
        "payload_count": payload_count,
        "output_jsonl": str(output_jsonl),
        "validation": validation,
    }


def main() -> int:
    args = parse_args()
    report = build_payloads(
        args.input_csv,
        args.output_jsonl,
        require_all_annotated=args.require_all_annotated,
    )
    if not report["valid"]:
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return 1
    print(f"prepared {report['payload_count']} feedback payload(s) to {args.output_jsonl}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
