#!/usr/bin/env python3
"""Estimate hard-case review capacity for fixed human time budgets.

Input is the privacy-safe CSV generated by `export_hard_cases_csv.py`. The report
answers an ops question without model calls: how many unresolved cases can a
reviewer handle in 30/60/120 minutes, using the same deterministic effort estimate
as the review-batch selector.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from tools.select_hard_case_review_batch import REQUIRED_FIELDS, estimate_review_effort_minutes
from tools.validate_hard_cases_csv import validate_csv

DEFAULT_BUDGETS = [30, 60, 120]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Report how many unresolved hard cases fit in review time budgets."
    )
    parser.add_argument("input_csv", type=Path, help="CSV generated by tools/export_hard_cases_csv.py")
    parser.add_argument("output_json", type=Path, help="Destination capacity report JSON path")
    parser.add_argument(
        "--budgets",
        default=",".join(str(value) for value in DEFAULT_BUDGETS),
        help="Comma-separated minute budgets (default: 30,60,120)",
    )
    return parser.parse_args()


def _parse_budgets(raw_budgets: str) -> list[int]:
    budgets: list[int] = []
    for raw_value in raw_budgets.split(","):
        raw_value = raw_value.strip()
        if not raw_value:
            continue
        try:
            value = int(raw_value)
        except ValueError as exc:
            raise ValueError("budgets must be comma-separated positive integers") from exc
        if value <= 0:
            raise ValueError("budgets must be positive integers")
        budgets.append(value)
    if not budgets:
        raise ValueError("at least one review budget is required")
    return sorted(set(budgets))


def _priority(row: dict[str, str]) -> int:
    return int(row["review_priority"])


def _read_rows(input_csv: Path) -> list[dict[str, str]]:
    with input_csv.open(encoding="utf-8", newline="") as input_file:
        reader = csv.DictReader(input_file)
        if reader.fieldnames is None:
            raise ValueError("CSV must contain a header row")
        missing = REQUIRED_FIELDS - set(reader.fieldnames)
        if missing:
            raise ValueError(f"CSV missing required field(s): {', '.join(sorted(missing))}")
        return [dict(row) for row in reader]


def _is_unresolved(row: dict[str, str]) -> bool:
    feedback = (row.get("user_feedback") or "").strip()
    return feedback == "" or feedback == "unknown"


def _capacity_for_budget(rows: list[dict[str, str]], budget_minutes: int) -> dict[str, Any]:
    used_minutes = 0
    selected: list[dict[str, Any]] = []
    for row in rows:
        effort = estimate_review_effort_minutes(row)
        if used_minutes + effort > budget_minutes:
            continue
        selected.append(
            {
                "scan_id": row["scan_id"],
                "review_priority": _priority(row),
                "review_effort_minutes": effort,
                "status": row["status"],
                "city_id": (row.get("city_id") or "no_city").strip() or "no_city",
            }
        )
        used_minutes += effort
    return {
        "budget_minutes": budget_minutes,
        "case_count": len(selected),
        "used_minutes": used_minutes,
        "remaining_minutes": budget_minutes - used_minutes,
        "scan_ids": [item["scan_id"] for item in selected],
        "items": selected,
    }


def report_review_capacity(input_csv: Path, output_json: Path, *, budgets: list[int] | None = None) -> dict[str, Any]:
    """Write and return a deterministic review-capacity report."""
    budgets = DEFAULT_BUDGETS if budgets is None else sorted(set(budgets))
    validation = validate_csv(input_csv)
    if not validation["valid"]:
        return {
            "schema_version": "hard-case-review-capacity-v1",
            "input_csv": str(input_csv),
            "valid": False,
            "validation": validation,
            "errors": ["input CSV is invalid; aborting capacity report"],
        }

    rows = _read_rows(input_csv)
    unresolved = [row for row in rows if _is_unresolved(row)]
    unresolved.sort(key=lambda row: (-_priority(row), row["created_at"], row["scan_id"]))
    unresolved_effort = sum(estimate_review_effort_minutes(row) for row in unresolved)

    report = {
        "schema_version": "hard-case-review-capacity-v1",
        "input_csv": str(input_csv),
        "valid": True,
        "input_record_count": len(rows),
        "unresolved_count": len(unresolved),
        "unresolved_estimated_effort_minutes": unresolved_effort,
        "budgets": [_capacity_for_budget(unresolved, budget) for budget in budgets],
        "policy": {
            "sort": "unresolved only, review_priority desc, created_at asc, scan_id asc",
            "effort_estimator": "tools.select_hard_case_review_batch.estimate_review_effort_minutes",
        },
    }
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return report


def main() -> int:
    args = parse_args()
    budgets = _parse_budgets(args.budgets)
    report = report_review_capacity(args.input_csv, args.output_json, budgets=budgets)
    if report["valid"]:
        summary = ", ".join(
            f"{budget['budget_minutes']}min={budget['case_count']} case(s)"
            for budget in report["budgets"]
        )
        print(f"review capacity: {summary} to {args.output_json}")
    else:
        print(f"review capacity invalid: {len(report['errors'])} error(s), 0 artifact(s)")
    return 0 if report["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
