#!/usr/bin/env python3
"""Run Cicero hard-case ops helpers as one privacy-safe dry-run pipeline.

Input is the review CSV generated by `export_hard_cases_csv.py`. The pipeline
validates it, writes a summary JSON, selects a bounded unresolved review batch,
and prepares inspectable feedback payloads for already annotated rows. It never
calls the API and never mutates the hard-case JSONL store.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from tools.prepare_hard_case_feedback_payloads import build_payloads
from tools.export_hard_case_review_markdown import export_review_markdown
from tools.select_hard_case_review_batch import select_review_batch
from tools.summarize_hard_cases_csv import summarize_csv
from tools.validate_hard_cases_csv import validate_csv


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run validate → summarize → select batch → prepare payloads without API side effects."
    )
    parser.add_argument("input_csv", type=Path, help="Annotated CSV generated by tools/export_hard_cases_csv.py")
    parser.add_argument("output_dir", type=Path, help="Directory receiving dry-run artifacts")
    parser.add_argument("--top", type=int, default=5, help="Maximum rows per summary top list (default: 5)")
    parser.add_argument("--batch-limit", type=int, default=20, help="Maximum unresolved rows in review batch")
    parser.add_argument("--max-per-city", type=int, default=8, help="Maximum selected rows per city bucket")
    parser.add_argument("--max-per-status", type=int, default=12, help="Maximum selected rows per status bucket")
    parser.add_argument(
        "--require-all-annotated",
        action="store_true",
        help="Fail validation/payload preparation if at least one row has no user_feedback label.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the full machine-readable dry-run report instead of a compact line.",
    )
    return parser.parse_args()


def run_pipeline(
    input_csv: Path,
    output_dir: Path,
    *,
    top: int = 5,
    batch_limit: int = 20,
    max_per_city: int = 8,
    max_per_status: int = 12,
    require_all_annotated: bool = False,
) -> dict[str, Any]:
    """Create all local dry-run artifacts and return a compact ops report."""
    output_dir.mkdir(parents=True, exist_ok=True)
    summary_path = output_dir / "hard-case-summary.json"
    batch_path = output_dir / "hard-case-review-batch.json"
    payloads_path = output_dir / "hard-case-feedback-payloads.jsonl"
    review_markdown_path = output_dir / "hard-case-review-sheet.md"

    validation = validate_csv(input_csv, require_all_annotated=require_all_annotated)
    report: dict[str, Any] = {
        "schema_version": "hard-case-review-pipeline-v1",
        "input_csv": str(input_csv),
        "output_dir": str(output_dir),
        "valid": validation["valid"],
        "validation": validation,
        "artifacts": {},
    }

    if not validation["valid"]:
        return report

    summary = summarize_csv(input_csv, summary_path, top=top)
    batch = select_review_batch(
        input_csv,
        batch_path,
        limit=batch_limit,
        max_per_city=max_per_city,
        max_per_status=max_per_status,
    )
    payloads = build_payloads(input_csv, payloads_path, require_all_annotated=require_all_annotated)
    review_markdown = export_review_markdown(batch_path, review_markdown_path)

    report.update(
        {
            "record_count": summary["record_count"],
            "annotated_count": validation["annotated_count"],
            "selected_review_count": batch["selected_count"],
            "payload_count": payloads["payload_count"],
            "artifacts": {
                "summary_json": str(summary_path),
                "review_batch_json": str(batch_path),
                "review_markdown": str(review_markdown_path),
                "feedback_payloads_jsonl": str(payloads_path),
            },
            "review_markdown_item_count": review_markdown["item_count"],
            "top_city_status_pairs": summary["top_city_status_pairs"],
        }
    )
    return report


def main() -> int:
    args = parse_args()
    report = run_pipeline(
        args.input_csv,
        args.output_dir,
        top=args.top,
        batch_limit=args.batch_limit,
        max_per_city=args.max_per_city,
        max_per_status=args.max_per_status,
        require_all_annotated=args.require_all_annotated,
    )
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    elif report["valid"]:
        print(
            f"pipeline ok: {report['record_count']} row(s), "
            f"{report['annotated_count']} annotated, "
            f"{report['selected_review_count']} selected, "
            f"{report['payload_count']} payload(s) to {args.output_dir}"
        )
    else:
        print(
            f"pipeline invalid: {report['validation']['row_count']} row(s), "
            f"{len(report['validation']['errors'])} error(s), 0 artifact(s)"
        )
    return 0 if report["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
