#!/usr/bin/env python3
"""Select a bounded, privacy-safe Cicero hard-case review batch.

Input: CSV generated by `export_hard_cases_csv.py`, optionally annotated by ops.
Output: compact JSON batch of unresolved rows (`user_feedback` blank or `unknown`),
ranked by review priority while capping city/status concentration so a reviewer gets
a diverse, actionable queue instead of 20 near-duplicates from one failure mode.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path
from typing import Any

REQUIRED_FIELDS = {
    "review_priority",
    "scan_id",
    "status",
    "score",
    "created_at",
    "model_version",
    "city_id",
    "candidate_monument_id",
    "user_feedback",
    "notes",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Select a bounded unresolved hard-case review batch from a privacy-safe CSV."
    )
    parser.add_argument("input_csv", type=Path, help="CSV generated by tools/export_hard_cases_csv.py")
    parser.add_argument("output_json", type=Path, help="Destination JSON batch path")
    parser.add_argument("--limit", type=int, default=20, help="Maximum selected rows (default: 20)")
    parser.add_argument(
        "--max-per-city",
        type=int,
        default=8,
        help="Maximum selected rows per city_id/no_city bucket (default: 8)",
    )
    parser.add_argument(
        "--max-per-status",
        type=int,
        default=12,
        help="Maximum selected rows per status bucket (default: 12)",
    )
    return parser.parse_args()


def _label(value: str | None, fallback: str) -> str:
    if value is None or not value.strip():
        return fallback
    return value.strip()


def _priority(row: dict[str, str]) -> int:
    try:
        return int(row["review_priority"])
    except ValueError as exc:
        raise ValueError(f"review_priority must be an integer for scan_id={row.get('scan_id', '')}") from exc


def estimate_review_effort_minutes(row: dict[str, str]) -> int:
    """Estimate human review effort for one privacy-safe hard-case row.

    The estimate is intentionally coarse: it helps an operator size a review batch
    without inspecting raw images or running a model. Values are minutes per case.
    """
    status = _label(row.get("status"), "missing_status")
    feedback = _label(row.get("user_feedback"), "")
    effort = 3
    if status == "not_found":
        effort += 2
    elif status == "low_confidence":
        effort += 1
    if feedback == "unknown":
        effort += 1
    if _label(row.get("candidate_monument_id"), ""):
        effort += 1
    if _label(row.get("notes"), ""):
        effort += 1
    return min(effort, 8)


def _read_rows(input_csv: Path) -> list[dict[str, str]]:
    with input_csv.open(encoding="utf-8", newline="") as input_file:
        reader = csv.DictReader(input_file)
        if reader.fieldnames is None:
            raise ValueError("CSV must contain a header row")
        missing = REQUIRED_FIELDS - set(reader.fieldnames)
        if missing:
            raise ValueError(f"CSV missing required field(s): {', '.join(sorted(missing))}")
        return [dict(row) for row in reader]


def select_review_batch(
    input_csv: Path,
    output_json: Path,
    *,
    limit: int = 20,
    max_per_city: int = 8,
    max_per_status: int = 12,
) -> dict[str, Any]:
    if limit <= 0:
        raise ValueError("limit must be a positive integer")
    if max_per_city <= 0:
        raise ValueError("max_per_city must be a positive integer")
    if max_per_status <= 0:
        raise ValueError("max_per_status must be a positive integer")

    rows = _read_rows(input_csv)
    unresolved = [
        row
        for row in rows
        if not (row.get("user_feedback") or "").strip()
        or (row.get("user_feedback") or "").strip() == "unknown"
    ]
    unresolved.sort(key=lambda row: (-_priority(row), row["created_at"], row["scan_id"]))

    by_city: Counter[str] = Counter()
    by_status: Counter[str] = Counter()
    selected: list[dict[str, Any]] = []
    skipped_due_to_caps = 0

    for row in unresolved:
        city = _label(row.get("city_id"), "no_city")
        status = _label(row.get("status"), "missing_status")
        if by_city[city] >= max_per_city or by_status[status] >= max_per_status:
            skipped_due_to_caps += 1
            continue
        selected.append(
            {
                "review_priority": _priority(row),
                "review_effort_minutes": estimate_review_effort_minutes(row),
                "scan_id": row["scan_id"],
                "status": status,
                "score": float(row["score"]),
                "created_at": row["created_at"],
                "model_version": row["model_version"],
                "city_id": city,
                "candidate_monument_id": row["candidate_monument_id"],
                "user_feedback": row["user_feedback"],
                "notes": row["notes"],
            }
        )
        by_city[city] += 1
        by_status[status] += 1
        if len(selected) == limit:
            break

    batch: dict[str, Any] = {
        "schema_version": "hard-case-review-batch-v1",
        "source_csv": str(input_csv),
        "input_record_count": len(rows),
        "unresolved_count": len(unresolved),
        "selected_count": len(selected),
        "estimated_review_effort_minutes": sum(
            int(item["review_effort_minutes"]) for item in selected
        ),
        "selection_policy": {
            "limit": limit,
            "max_per_city": max_per_city,
            "max_per_status": max_per_status,
            "sort": "review_priority desc, created_at asc, scan_id asc",
        },
        "counts_by_city": dict(sorted(by_city.items())),
        "counts_by_status": dict(sorted(by_status.items())),
        "skipped_due_to_caps": skipped_due_to_caps,
        "items": selected,
    }

    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(batch, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return batch


def main() -> int:
    args = parse_args()
    batch = select_review_batch(
        args.input_csv,
        args.output_json,
        limit=args.limit,
        max_per_city=args.max_per_city,
        max_per_status=args.max_per_status,
    )
    print(
        f"selected {batch['selected_count']} of {batch['unresolved_count']} unresolved hard-case row(s) "
        f"to {args.output_json}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
