#!/usr/bin/env python3
"""Summarize Cicero hard-case review CSV exports into actionable buckets.

The input is the privacy-safe CSV generated by `export_hard_cases_csv.py`.
The output is a compact JSON report for ops/product decisions: counts by status,
feedback, city and city/status pairs, plus the highest-priority unresolved rows.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path
from typing import Any

REQUIRED_FIELDS = {
    "review_priority",
    "scan_id",
    "status",
    "score",
    "created_at",
    "model_version",
    "city_id",
    "candidate_monument_id",
    "user_feedback",
    "notes",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize a privacy-safe hard-case review CSV into JSON action buckets."
    )
    parser.add_argument("input_csv", type=Path, help="CSV generated by tools/export_hard_cases_csv.py")
    parser.add_argument("output_json", type=Path, help="Destination JSON summary path")
    parser.add_argument(
        "--top",
        type=int,
        default=5,
        help="Maximum rows per top list (default: 5)",
    )
    return parser.parse_args()


def _label(value: str | None, fallback: str = "unlabeled") -> str:
    if value is None or not value.strip():
        return fallback
    return value.strip()


def _read_rows(input_csv: Path) -> list[dict[str, str]]:
    with input_csv.open(encoding="utf-8", newline="") as input_file:
        reader = csv.DictReader(input_file)
        if reader.fieldnames is None:
            raise ValueError("CSV must contain a header row")
        missing = REQUIRED_FIELDS - set(reader.fieldnames)
        if missing:
            raise ValueError(f"CSV missing required field(s): {', '.join(sorted(missing))}")
        return [dict(row) for row in reader]


def _priority(row: dict[str, str]) -> int:
    try:
        return int(row["review_priority"])
    except ValueError as exc:
        raise ValueError(f"review_priority must be an integer for scan_id={row.get('scan_id', '')}") from exc


def summarize_csv(input_csv: Path, output_json: Path, *, top: int = 5) -> dict[str, Any]:
    if top <= 0:
        raise ValueError("top must be a positive integer")

    rows = _read_rows(input_csv)
    by_status = Counter(_label(row["status"], "missing_status") for row in rows)
    by_feedback = Counter(_label(row["user_feedback"]) for row in rows)
    by_city = Counter(_label(row["city_id"], "no_city") for row in rows)
    by_city_status = Counter(
        f"{_label(row['city_id'], 'no_city')}|{_label(row['status'], 'missing_status')}" for row in rows
    )

    unresolved = [row for row in rows if not row["user_feedback"].strip() or row["user_feedback"] == "unknown"]
    unresolved.sort(key=lambda row: (-_priority(row), row["created_at"], row["scan_id"]))

    summary: dict[str, Any] = {
        "schema_version": "hard-case-summary-v1",
        "source_csv": str(input_csv),
        "record_count": len(rows),
        "counts_by_status": dict(sorted(by_status.items())),
        "counts_by_feedback": dict(sorted(by_feedback.items())),
        "top_cities": by_city.most_common(top),
        "top_city_status_pairs": by_city_status.most_common(top),
        "top_unresolved": [
            {
                "review_priority": _priority(row),
                "scan_id": row["scan_id"],
                "status": row["status"],
                "city_id": row["city_id"],
                "candidate_monument_id": row["candidate_monument_id"],
                "user_feedback": row["user_feedback"],
                "notes": row["notes"],
            }
            for row in unresolved[:top]
        ],
    }

    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return summary


def main() -> int:
    args = parse_args()
    summary = summarize_csv(args.input_csv, args.output_json, top=args.top)
    print(f"summarized {summary['record_count']} hard-case record(s) to {args.output_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
