#!/usr/bin/env python3
"""Validate an annotated Cicero hard-case review CSV before feedback reinjection.

This is a privacy-safe preflight for the ops loop: it checks schema, labels,
priorities and duplicate scan IDs, but it does not call the API or mutate the
hard-case JSONL store.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path
from typing import Any

REQUIRED_FIELDS = {
    "review_priority",
    "scan_id",
    "status",
    "score",
    "created_at",
    "model_version",
    "city_id",
    "candidate_monument_id",
    "user_feedback",
    "notes",
}
ALLOWED_STATUSES = {"low_confidence", "not_found"}
ALLOWED_FEEDBACK = {"correct", "wrong_monument", "unknown", "poor_angle", "too_dark", "other"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate an annotated hard-case review CSV before API reinjection."
    )
    parser.add_argument("input_csv", type=Path, help="CSV generated by tools/export_hard_cases_csv.py")
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print a machine-readable validation report instead of the compact text line.",
    )
    parser.add_argument(
        "--require-all-annotated",
        action="store_true",
        help="Fail if one or more review rows have an empty user_feedback label.",
    )
    return parser.parse_args()


def _is_blank(value: str | None) -> bool:
    return value is None or not value.strip()


def _validate_int(value: str, *, field: str, row_number: int, minimum: int, maximum: int) -> str | None:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return f"row {row_number}: {field} must be an integer"
    if not minimum <= parsed <= maximum:
        return f"row {row_number}: {field} must be between {minimum} and {maximum}"
    return None


def _validate_float(value: str, *, field: str, row_number: int, minimum: float, maximum: float) -> str | None:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return f"row {row_number}: {field} must be a number"
    if not minimum <= parsed <= maximum:
        return f"row {row_number}: {field} must be between {minimum:g} and {maximum:g}"
    return None


def validate_csv(input_csv: Path, *, require_all_annotated: bool = False) -> dict[str, Any]:
    errors: list[str] = []
    warnings: list[str] = []
    feedback_counts: Counter[str] = Counter()
    status_counts: Counter[str] = Counter()
    seen_scan_ids: set[str] = set()
    annotated_count = 0
    row_count = 0

    with input_csv.open(encoding="utf-8", newline="") as input_file:
        reader = csv.DictReader(input_file)
        if reader.fieldnames is None:
            return {
                "schema_version": "hard-case-csv-validation-v1",
                "valid": False,
                "row_count": 0,
                "annotated_count": 0,
                "counts_by_status": {},
                "counts_by_feedback": {},
                "errors": ["CSV must contain a header row"],
                "warnings": [],
            }

        missing = REQUIRED_FIELDS - set(reader.fieldnames)
        extra = set(reader.fieldnames) - REQUIRED_FIELDS
        if missing:
            errors.append(f"header: missing required field(s): {', '.join(sorted(missing))}")
        if extra:
            warnings.append(f"header: ignored extra field(s): {', '.join(sorted(extra))}")

        for row_number, row in enumerate(reader, start=2):
            row_count += 1
            scan_id = (row.get("scan_id") or "").strip()
            if not scan_id:
                errors.append(f"row {row_number}: scan_id must be non-empty")
            elif scan_id in seen_scan_ids:
                errors.append(f"row {row_number}: duplicate scan_id={scan_id}")
            else:
                seen_scan_ids.add(scan_id)

            priority_error = _validate_int(
                row.get("review_priority") or "",
                field="review_priority",
                row_number=row_number,
                minimum=0,
                maximum=100,
            )
            if priority_error:
                errors.append(priority_error)

            score_error = _validate_float(
                row.get("score") or "",
                field="score",
                row_number=row_number,
                minimum=0,
                maximum=1,
            )
            if score_error:
                errors.append(score_error)

            status = (row.get("status") or "").strip()
            if status not in ALLOWED_STATUSES:
                errors.append(f"row {row_number}: status must be low_confidence or not_found")
            else:
                status_counts[status] += 1

            if _is_blank(row.get("created_at")):
                errors.append(f"row {row_number}: created_at must be non-empty")
            if _is_blank(row.get("model_version")):
                errors.append(f"row {row_number}: model_version must be non-empty")

            feedback = (row.get("user_feedback") or "").strip()
            if feedback:
                if feedback not in ALLOWED_FEEDBACK:
                    errors.append(f"row {row_number}: user_feedback is not an allowed label")
                else:
                    annotated_count += 1
                    feedback_counts[feedback] += 1
            else:
                feedback_counts["unlabeled"] += 1
                if require_all_annotated:
                    errors.append(f"row {row_number}: user_feedback must be annotated")

            notes = (row.get("notes") or "").strip()
            if notes and len(notes) > 240:
                warnings.append(f"row {row_number}: notes longer than 240 characters; shorten before reinjection")

    return {
        "schema_version": "hard-case-csv-validation-v1",
        "valid": not errors,
        "row_count": row_count,
        "annotated_count": annotated_count,
        "counts_by_status": dict(sorted(status_counts.items())),
        "counts_by_feedback": dict(sorted(feedback_counts.items())),
        "errors": errors,
        "warnings": warnings,
    }


def main() -> int:
    args = parse_args()
    report = validate_csv(args.input_csv, require_all_annotated=args.require_all_annotated)
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        status = "valid" if report["valid"] else "invalid"
        print(
            f"{status}: {report['row_count']} row(s), "
            f"{report['annotated_count']} annotated, "
            f"{len(report['errors'])} error(s), {len(report['warnings'])} warning(s)"
        )
    return 0 if report["valid"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
